// AUTO-GENERATED by scripts/sync-game-ids.py — do not edit by hand.
// Source of truth: /Users/yin/code/games/games/games.json

(window as any).__GAME_UUID__ = '6af4f385-954f-436f-9dda-c0f1572dab88';
